Development
reproducible-biomedical-modeling/CRBM-Viz pull request #26
Opened 2019-10-09 20:47 UTC by gmarupilla

I added client id and domain to config and kept it in gitignore. I've added config.example.json which the user can copy paste as config.json and modify the contents for testing purposes. Or environment wise.

2019-10-11 00:03 UTC, bilalshaikh42 commented
The build and docker tests are failing. Could you make sure that the app builds properly outside your local environment? 
@gmarupilla

2019-10-11 14:12 UTC, gmarupilla commented
I've added `config.example.json` as a default config.. Or a template config..every time we want to build it.. We will copy example config to `config.json`
And then it'll work. It's a replacement for environment variable. Since in front-end app we cannot access environment variables

2019-10-11 17:04 UTC, bilalshaikh42 commented
> I've added `config.example.json` as a default config.. Or a template config..every time we want to build it.. We will copy example config to `config.json`
> And then it'll work. It's a replacement for environment variable. Since in front-end app we cannot access environment variables

I see that the config file contains just the Auth0 client id. In that case, it does not need to be hidden and should be included in the source to allow for automatic building and deployment

https://community.auth0.com/t/client-id-vs-secret/9558

2019-10-13 14:43 UTC, gmarupilla commented
> > I've added `config.example.json` as a default config.. Or a template config..every time we want to build it.. We will copy example config to `config.json`
> > And then it'll work. It's a replacement for environment variable. Since in front-end app we cannot access environment variables
> 
> I see that the config file contains just the Auth0 client id. In that case, it does not need to be hidden and should be included in the source to allow for automatic building and deployment
> 
> https://community.auth0.com/t/client-id-vs-secret/9558

Still, I think it's better to have such things in a configuration file rather than being hardcoded into code itself. Here's one use case why, I have my own personal auth0 account which I use to experiment/test the code that I write, if I modify client id in code, I'll need to exempt it from commits every single time I change anything else. With a configuration file like this, user can modify configuration with ease according to different environments. To resolve this, I added docker rule to copy config.example.json (which is default config for heroku) to config.json. Moreover, more things are also added to config, and will keep on increasing in the future.

2019-10-13 21:24 UTC, bilalshaikh42 commented
> > > I've added `config.example.json` as a default config.. Or a template config..every time we want to build it.. We will copy example config to `config.json`
> > > And then it'll work. It's a replacement for environment variable. Since in front-end app we cannot access environment variables
> > 
> > 
> > I see that the config file contains just the Auth0 client id. In that case, it does not need to be hidden and should be included in the source to allow for automatic building and deployment
> > https://community.auth0.com/t/client-id-vs-secret/9558
> 
> Still, I think it's better to have such things in a configuration file rather than being hardcoded into code itself. Here's one use case why, I have my own personal auth0 account which I use to experiment/test the code that I write, if I modify client id in code, I'll need to exempt it from commits every single time I change anything else. With a configuration file like this, user can modify configuration with ease according to different environments. To resolve this, I added docker rule to copy config.example.json (which is default config for heroku) to config.json. Moreover, more things are also added to config, and will keep on increasing in the future.

Got it. In that case, lets make use of the environment.ts and environment.prod.ts files in the environments folder. The auth service has a good example on how I used the files to change based on various environments. You could even add a new environment for your development environment. Thi way, everything needed to build the app (currently the build step is failing in the node workflow) is present in default configurations at all times. When building, use the --configuration flag
Here is a good guide for it:
[Link]( https://blog.angularindepth.com/becoming-an-angular-environmentalist-45a48f7c20d8)

2019-10-15 19:31 UTC, gmarupilla commented
> > > > I've added `config.example.json` as a default config.. Or a template config..every time we want to build it.. We will copy example config to `config.json`
> > > > And then it'll work. It's a replacement for environment variable. Since in front-end app we cannot access environment variables
> > > 
> > > 
> > > I see that the config file contains just the Auth0 client id. In that case, it does not need to be hidden and should be included in the source to allow for automatic building and deployment
> > > https://community.auth0.com/t/client-id-vs-secret/9558
> > 
> > 
> > Still, I think it's better to have such things in a configuration file rather than being hardcoded into code itself. Here's one use case why, I have my own personal auth0 account which I use to experiment/test the code that I write, if I modify client id in code, I'll need to exempt it from commits every single time I change anything else. With a configuration file like this, user can modify configuration with ease according to different environments. To resolve this, I added docker rule to copy config.example.json (which is default config for heroku) to config.json. Moreover, more things are also added to config, and will keep on increasing in the future.
> 
> Got it. In that case, lets make use of the environment.ts and environment.prod.ts files in the environments folder. The auth service has a good example on how I used the files to change based on various environments. You could even add a new environment for your development environment. Thi way, everything needed to build the app (currently the build step is failing in the node workflow) is present in default configurations at all times. When building, use the --configuration flag
> Here is a good guide for it:
> [Link](https://blog.angularindepth.com/becoming-an-angular-environmentalist-45a48f7c20d8)

Thanks for the info, moved configs to environment files.

2019-10-15 19:41 UTC, gmarupilla commented
I guess tests are failing in the components you've written. Can you look into it?

2019-10-15 20:23 UTC, bilalshaikh42 commented
Yup tests are not yet passing per #9 .  For now we can only assume it works if building. I'll merge this in

2019-10-15 20:37 UTC, bilalshaikh42 requested changes

2019-10-15 20:37 UTC, bilalshaikh42 commented on CRBM-Viz/angular.json
> +              "optimization": true,
This might be very slow for development. Up to you, but we can change the optimization and AOT off since we dont be deploying using this environment

2019-10-15 20:37 UTC, bilalshaikh42 commented on CRBM-Viz/src/app/Components/loading-spinner/loading-spinner.component.html
> +        <div class="span12" style="height: 80vh; padding-top: 30vh; padding-left: 30vw;">
Can you move the styles to the sass? If there is a reason for it to be here, its fine in that case

2019-10-15 20:37 UTC, bilalshaikh42 commented on CRBM-Viz/src/app/Components/loading-spinner/loading-spinner.component.sass
> +@keyframes lds-eclipse
Angular material already has a spinner defined. 
Can we use that instead for simplicity and consistancy? 
https://material.angular.io/components/progress-spinner/overviewhttps://material.angular.io/components/progress-spinner/overview

2019-10-15 20:37 UTC, bilalshaikh42 commented on CRBM-Viz/src/app/Layout/links/links.component.ts
> -  ngOnInit() {}
As mentioned in #29 this component will be deleted, so it is not a good idea to have the profile load here. In any case, it is probably not a good idea to have the profile load in an unrelated component. Can this be moved to the main app component?

2019-10-15 20:37 UTC, bilalshaikh42 commented on CRBM-Viz/src/app/Services/auth0.service.ts
> +import { environment as config }  from 'src/environments/environment';
This is just messy. Lets change the config name below to environment

2019-10-15 20:37 UTC, bilalshaikh42 commented on CRBM-Viz/src/app/Services/auth0.service.ts
> +      domain: config.auth0.domain,
Change this to environment.autho0

2019-10-15 20:37 UTC, bilalshaikh42 commented on CRBM-Viz/src/app/Services/auth0.service.ts
> +        client_id: config.auth0.clientId,
Likewise here

2019-10-21 01:03 UTC, merged