feat(dispatch,simulators,platform): prominently display down status on apps
reproducible-biomedical-modeling/CRBM-Viz pull request #3237
Opened 2021-10-16 04:14 UTC by jonrkarr

closes #3210

When a status of a relevant service to an app is `down`, displays a red bar at the bottom of each page of the app. The bar is displayed similar to the privacy policy notice.

Todo
- [ ] Link to new `/health` endpoint after #3308 is finished

2021-10-16 18:09 UTC, bilalshaikh42 commented
I don't want to end up tying the structure of the status checks to the app. This is bound to break and cause lots of issues. The status checks were set quite quickly so more thought would be needed on what portions/names to test. 
One alternative is to just go through all the statuses and show the error if anything is down.

2021-10-16 18:16 UTC, bilalshaikh42 requested changes

2021-10-16 18:16 UTC, bilalshaikh42 commented on apps/simulators/src/app/app.component.ts
> +    this.status$ = this.systemStatusService.getAppStatus([
Using as here is bound to cause issues If any network requests fail. In general using as should be avoided as all checks for null/undefined are lost. This leads to errors such as the one caused by the simulators response which would otherwise be caught by the compiler

2021-10-16 18:16 UTC, bilalshaikh42 commented on libs/datamodel/common/src/lib/common/system-status.ts
> +export interface SystemStatus {
I really don't think this should be included in the data model. This will be adding another external dependency that now needs to be kept in sync. If we really want to have it, it should at least be completely encapsulated by the service and not exported for use by other apps

2021-10-18 05:17 UTC, bilalshaikh42 commented
Closing in favor of  a solution that utilizes #3308 
Health endpoint will return either 200 or 503, which is sufficient to point users to status.biosimulations.org for details

2021-10-18 12:47 UTC, jonrkarr commented
Most of this PR doesn't directly relate to where status is checked. That part can be replaced. 

While I did define an interface, I chose not to make the apps use this. Somewhere the apps need to declare the services that are relevant to them.

2021-10-20 16:45 UTC, jonrkarr commented on libs/datamodel/common/src/lib/common/system-status.ts
> +export interface SystemStatus {
Removed this logic here in favor of moving it to the health module.

2021-10-20 17:32 UTC, jonrkarr commented on libs/api/angular-client/src/lib/health/health.service.ts
> +    return of(true);
Get health here

2021-10-20 17:35 UTC, jonrkarr commented on nx.json
> +        "scope:simulators",
The scope of the angular-api-client had to be broadened to allow the simulators app to also get health information from the single health endpoint that will be added to the BioSimulations API through the angular-api-client.

2021-10-20 18:03 UTC, bilalshaikh42 commented
the simulators endpoint will need its own health endpoint anyway, so we can
use that. I would really like to avoid broadening the scope as then the
simulators app will have dependencies on the main API which we definitely
do not want

On Wed, Oct 20, 2021 at 1:36 PM Jonathan Karr ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In nx.json
> <https://github.com/biosimulations/biosimulations/pull/3237#discussion_r733003835>
> :
>
> > @@ -86,6 +86,7 @@
>      "api-angular-client": {
>        "tags": [
>          "scope:simulations",
> +        "scope:simulators",
>
> The scope of the angular-api-client had to be broadened to allow the
> simulators app to also get health information from the single health
> endpoint that will be added to the BioSimulations API through the
> angular-api-client.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/biosimulations/biosimulations/pull/3237#pullrequestreview-784801199>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHX4FIDUVPXDCR6PYXUSQNTUH34YTANCNFSM5GDGDO3Q>
> .
>

2021-10-20 18:46 UTC, jonrkarr commented
I agree there should be different health information for different apps. This is what I was starting to set up. I changed this because you discussed 1 health endpoint.

2021-10-20 18:59 UTC, jonrkarr commented on nx.json
> +        "scope:simulators",
I separated health checking for the two APIs

2021-10-20 22:33 UTC, bilalshaikh42 commented
We should now have the following deployed: 

API: /health/status 
SimAPI: /health 

the /health on the API is not complete, meaning it does not check for other dependencies that may have issues. this is to prevent kubernetes from killing the API just because the database is down and triggering a failure cascade. The front end should use /health/status to get a more accurate status from the user's perspective

2021-10-20 22:40 UTC, bilalshaikh42 requested changes

2021-10-20 22:40 UTC, bilalshaikh42 commented on apps/platform/src/app/app.component.spec.ts
> +    // const fixture = TestBed.createComponent(AppComponent);
We can just mock the health service to prevent any issues

2021-10-20 22:40 UTC, bilalshaikh42 commented on apps/simulators/src/app/app.component.spec.ts
> +    //const fixture = TestBed.createComponent(AppComponent);
Same here

2021-10-20 22:40 UTC, bilalshaikh42 commented on libs/config/common/src/lib/endpoints.ts
>    private api: string;
Changes in this file are already done in #3308 so can be reverted

2021-10-20 22:41 UTC, jonrkarr commented on apps/platform/src/app/app.component.spec.ts
> +    // const fixture = TestBed.createComponent(AppComponent);
This is because of the updater.

2021-10-20 22:41 UTC, jonrkarr commented on apps/simulators/src/app/app.component.spec.ts
> +    //const fixture = TestBed.createComponent(AppComponent);
Same as above

2021-10-20 22:44 UTC, bilalshaikh42 commented on apps/platform/src/app/app.component.spec.ts
> +    // const fixture = TestBed.createComponent(AppComponent);
The update service for the PWA?

2021-10-20 23:12 UTC, jonrkarr commented on libs/config/common/src/lib/endpoints.ts
>    private api: string;
I removed the endpoint method I created.

I needed to correct the simulators endpoint method.

2021-10-20 23:27 UTC, jonrkarr commented
Ready to merge. 

The status banner displays once the response from the health endpoint fails. If there's a delay, the banner will pop up after a short delay. When the API is working, users won't see the banner.

The banner appears at the bottom of each page and can be dismissed. The banner includes a link to https://status.biosimulations.org.

2021-10-26 07:50 UTC, merged

2021-10-26 07:51 UTC, jonrkarr commented
Lint failure fixed in another branch.