feat(dispatch): recorded simulator versions and digests for simulation runs
reproducible-biomedical-modeling/CRBM-Viz pull request #3318
Opened 2021-10-19 05:42 UTC by jonrkarr

closes #3195

- Uses simulators database to validate requested simulator/version
- Raises BadRequestException if an image isn't registered for the requested simulator/version
- Saves digest (hash) for simulator/version to `SimulationRun`
- Added common data models for simulators and simulation runs
- Added simulatorDigest to SimulationRunUpdate. I added this when thinking about using the SBatch service to get image digests. This could be removed. I ended up not using this and instead getting digests from the simulators database.

@bilalshaikh42 the key thing to review is the integration of the simulator API (L307 of `apps/api/src/simulation-run/simulation-run.service.ts`).

2021-10-19 05:43 UTC, jonrkarr commented on apps/api/src/simulation-run/simulation-run.service.ts
> +    const url = this.endpoints.getSimulatorsEndpoint(run.simulator, run.simulatorVersion);
Here's where the requested simulator/version is checked and the digest is obtained.

2021-10-19 14:45 UTC, bilalshaikh42 requested changes
The check and getting digest looks good.

2021-10-19 14:45 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.service.ts
> +  private endpoints = new Endpoints();
Need to pass in the env here from the config service

2021-10-19 14:45 UTC, bilalshaikh42 commented on libs/datamodel/api/src/lib/core/simulationRun.ts
> +    description: 'Digest of the simulation tool for the simulation run',
Do we want the digest to be changeable?

2021-10-19 14:45 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.service.ts
> +      newSimulationRun.simulatorVersion = simulatorResponse.data.version;
Why are we overriding the version here? Is it possible this is different from what the user requested?

2021-10-19 14:45 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.service.ts
> +    const url = this.endpoints.getSimulatorsEndpoint(run.simulator, run.simulatorVersion);
The check and info looks good.

2021-10-19 14:47 UTC, bilalshaikh42 commented on libs/datamodel/api/src/lib/core/simulationRun.ts
> +    description: 'Digest of the simulation tool for the simulation run',
I see your comment about this now. I agree we should remove this as we don't want to have this field change

2021-10-19 14:48 UTC, jonrkarr commented on apps/api/src/simulation-run/simulation-run.service.ts
> +      newSimulationRun.simulatorVersion = simulatorResponse.data.version;
This translates "latest" into a specific version. If the user requests and unregistered version, they would get an error.

2021-10-19 14:51 UTC, jonrkarr commented on libs/datamodel/api/src/lib/core/simulationRun.ts
> +    description: 'Digest of the simulation tool for the simulation run',
I'll remove this. This was because I was thinking about getting the digest from the Singularity image itself. Mainly to cover the possible case that the simulators database has diverged from the HPC environment because the refreshing of an image failed. Getting the digest from Singularity doesn't appear to be straightforward.

2021-10-19 15:42 UTC, jonrkarr commented on libs/api/nest-client/src/lib/simulation-run.service.ts
> -            `${this.endpoint}run/${id}`,
@bilalshaikh42 this seemed incorrect. Shouldn't this be `runs` plural?

2021-10-19 15:45 UTC, jonrkarr commented on apps/api/src/simulation-run/simulation-run.service.ts
> +  private endpoints = new Endpoints();
Done.

@bilalshaikh42 most uses of `Endpoints` don't pass an environment. Is the argument only needed for use in servers?

2021-10-19 15:45 UTC, jonrkarr commented on libs/datamodel/api/src/lib/core/simulationRun.ts
> +    description: 'Digest of the simulation tool for the simulation run',
Removed.

2021-10-19 16:50 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.service.ts
> +  private endpoints = new Endpoints();
Yup. On the front ends, the endpoints class will use the environment as defined in the environment file, since it is only changeable  at compile time. 

On the server, loading the environment dynamically is possible, so we can set an environment variable that can be read from the config service.

2021-10-19 16:53 UTC, jonrkarr commented on apps/api/src/simulation-run/simulation-run.service.ts
> +  private getSimulator(simulator: string, simulatorVersion: string): Promise<ISimulator | null | false> {
@bilalshaikh42 this needs to be tested. I can't test because I can't run the API.

2021-10-19 17:45 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.service.ts
> +      newSimulationRun.simulatorVersion = simulatorResponse.data.version;
That makes sense

2021-10-19 17:46 UTC, bilalshaikh42 commented on libs/api/nest-client/src/lib/simulation-run.service.ts
> -            `${this.endpoint}run/${id}`,
Either works to maintain compatibility with the older version. But yes, runs is preferred

2021-10-19 17:47 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.service.ts
> +  private getSimulator(simulator: string, simulatorVersion: string): Promise<ISimulator | null | false> {
will do

2021-10-19 18:52 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.service.ts
> +  private getSimulator(simulator: string, simulatorVersion: string): Promise<ISimulator | null | false> {
Does not seem to be working. I am working on debugging it. What is the issue with running the API? The docker image/compose file in the .dev container should be an easy way to set up the environment. If you open the directory with vscode it should prompt if you want to open up the repo in the dev container

2021-10-19 18:54 UTC, jonrkarr commented on apps/api/src/simulation-run/simulation-run.service.ts
> +      newSimulationRun.simulatorVersion = simulatorResponse.data.version;
Basically, this is to make the provenance of simulation results more concrete.

2021-10-19 19:44 UTC, bilalshaikh42 commented
@check-spelling-bot apply changes.

2021-10-19 19:44 UTC, bilalshaikh42 approved these changes

2021-10-19 20:03 UTC, merged

2021-10-20 00:35 UTC, biosimulations-daemon commented
:tada: This PR is included in version 5.8.0 :tada:

The release is available on [GitHub release](https://github.com/biosimulations/biosimulations/releases/tag/v5.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: