refactor(api): commented out unused buggy endpoint
reproducible-biomedical-modeling/CRBM-Viz pull request #3325
Opened 2021-10-20 07:11 UTC by jonrkarr

closes #3240

Also
- Removed redundant endpoint methods
- Clarified names of arguments of endpoint methods; made consistent with terminology in Swagger documentation

2021-10-20 14:41 UTC, bilalshaikh42 requested changes

2021-10-20 14:41 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.controller.ts
> +  /*
This method is used when developing and testing.  Since it requires authentication, it should not be confusing for users/reviewers as they will not have permission to call it. I would prefer to leave it in here

2021-10-20 14:41 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.service.ts
> +  // SimulationRunField,
Same here with leaving in in for the above method to work

2021-10-20 15:56 UTC, jonrkarr commented on apps/api/src/simulation-run/simulation-run.controller.ts
> +  /*
I replaced this with a simpler method that returns the list of simulation runs with all attributes.

Alternatively, the method could be debugged to properly return selected fields indicated via query arguments.

2021-10-20 15:56 UTC, jonrkarr commented on apps/api/src/simulation-run/simulation-run.service.ts
> +  // SimulationRunField,
Updated accordingly

2021-10-20 17:18 UTC, bilalshaikh42 commented on apps/api/src/simulation-run/simulation-run.controller.ts
> +  /*
I would prefer to debug it as some point and eventually add consistent options to select specific fields to all the endpoints

2021-10-20 17:27 UTC, jonrkarr commented on apps/api/src/simulation-run/simulation-run.controller.ts
> +  /*
Let's merge this and create a separate issue.

2021-10-20 17:28 UTC, merged

2021-10-24 18:19 UTC, biosimulations-daemon commented
:tada: This PR is included in version 5.9.0 :tada:

The release is available on [GitHub release](https://github.com/biosimulations/biosimulations/releases/tag/v5.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: