feat(simulators): added combined id/version property
reproducible-biomedical-modeling/CRBM-Viz pull request #3335
Opened 2021-10-20 21:59 UTC by jonrkarr

First steps toward #3164 

`idVersion` property is set just before saving/updating to database because I don't believe MongoDB has a great way to handle this. Pre-save hooks don't cover updating. Functions for defaults only apply when the value isn't directly set. Virtual properties can't be searched.

The simulators database could be migrated with the Python script below. I already ran this for the `dev` database. The first step saves a copy locally in case of any of problems.
```python
import json
import requests
import subprocess

response = requests.get('https://api.biosimulators.org/simulators?includeTests=true')
response.raise_for_status()
simulators = response.json()
with open('simulators.json', 'w') as file:
    json.dump(simulators, file)

response2 = requests.post('https://auth.biosimulations.org/oauth/token', json={
    'client_id': '...',
    'client_secret': '...',
    'audience': 'api.biosimulators.org',
    "grant_type": "client_credentials",
})
response2.raise_for_status()
response_data = response2.json()
auth = {'Authorization': response_data['token_type'] + ' ' + response_data['access_token']}

response2 = requests.delete(
    'https://api.biosimulators.org/simulators', json=simulator, headers=auth)
response2.raise_for_status()

for simulator in simulators:
    print(simulator['id'])

    response2 = requests.post(
        'https://api.biosimulators.org/simulators', json=simulator, headers=auth)
    response2.raise_for_status()
```

2021-10-20 22:23 UTC, bilalshaikh42 commented
I am bit unclear as to what the purpose of this is.

2021-10-20 22:25 UTC, bilalshaikh42 requested changes

2021-10-20 22:25 UTC, bilalshaikh42 commented on libs/simulators/database-models/src/lib/simulator.ts
> +    index: true,
We don't want to have this index here because we are setting a compound index below

2021-10-20 22:25 UTC, bilalshaikh42 commented on libs/simulators/database-models/src/lib/simulator.ts
> +SimulatorSchema.index({ id: 1, version: 1 }, { unique: false });
Why are we setting this to false? Each entry should have a unique id/version combination correct?

2021-10-20 22:29 UTC, bilalshaikh42 commented on libs/config/common/src/lib/urls.ts
> +    simulatorsApi: 'http://localhost:3333/',
This needs to be changed back. Is any of the code still using this for the URLs instead of the Endpoints?

2021-10-20 23:02 UTC, jonrkarr commented on libs/config/common/src/lib/urls.ts
> +    simulatorsApi: 'http://localhost:3333/',
That was a mistake. The code does use the URLs, mainly for hyperlinks. This was only partially refactored.

2021-10-20 23:04 UTC, jonrkarr commented
This follows #3164. A compound unique constraint would no longer be needed because its replaced by a unique constraint on a single attribute whose value is already a compound of id and version.

2021-10-21 16:15 UTC, bilalshaikh42 commented
Closing based on decision to close #3164

2021-10-21 16:15 UTC, closed without merging