docs: add glossary for common terms
reproducible-biomedical-modeling/CRBM-Viz pull request #4108
Opened 2022-02-01 15:34 UTC by bilalshaikh42

2022-02-01 15:39 UTC, jonrkarr commented
Embedding the entire glossary in every page seems a bit repetitive. Would a more prominent top-level menu item be sufficient?

2022-02-01 15:41 UTC, jonrkarr requested changes

2022-02-01 15:41 UTC, jonrkarr commented on docs/snippets/glossary.md
> +*[SED-ML]: Simulation Experiment Description Markup Language
I think it would be helpful to sort this in alphabetical order

2022-02-01 15:41 UTC, jonrkarr commented on docs/index.md
> +--8<-- "glossary.md"
Rather than embedding into every page, the index could be added to the menu via `.pages`

2022-02-01 19:02 UTC, bilalshaikh42 commented on docs/index.md
> +--8<-- "glossary.md"
> 
The glossary isn't actually displayed but provides tooltips over the words defined across the page. 
This page has a example of this extension https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#configuration

2022-02-02 14:06 UTC, merged

2022-02-03 04:14 UTC, biosimulations-daemon commented
:tada: This PR is included in version 9.0.0 :tada:

The release is available on [GitHub release](https://github.com/biosimulations/biosimulations/releases/tag/v9.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: