fix: added form value handler for custom simulation archive creation req
reproducible-biomedical-modeling/CRBM-Viz pull request #4850
Opened 2024-11-19 15:54 UTC by AlexPatrie

## _*What does this PR do?*_
### As required by the Biosimulations `1.0` release, this PR contains the following content:
- fix(ui): Fixes request logic handler in `platform/customize-simulation.component` for custom simulation archive creation calls.
- fix(style): Fixes DOM element family justifications in `platform/simulations/view` result visualization component.
- feat: Adds an auto-generated `<plot>` of all output observable results within the `<listOfOutputs>` specification for all archives created via the `simulation-project-utils/create-project` component.
- Additional adjustments as needed ahead of the `1.0` release.

2024-11-19 20:19 UTC, jcschaff requested changes
please clarify

2024-11-19 20:19 UTC, jcschaff commented on apps/platform/src/app/components/run/customize-simulation/customize-simulation.component.ts
> +  public _createNewArchive(queryParams: ReRunQueryParams): Promise<Blob | null> {
@AlexPatrie is _createNewArchive() used at all?  you introduced a new method, but not a new usage of this method.

2024-11-19 23:30 UTC, AlexPatrie commented on apps/platform/src/app/components/run/customize-simulation/customize-simulation.component.ts
> +  public _createNewArchive(queryParams: ReRunQueryParams): Promise<Blob | null> {
Unused content was removed.

2024-11-20 20:33 UTC, jcschaff approved these changes
looks reasonable, assumed you tested it locally - approved.

2024-11-25 18:15 UTC, merged

2024-11-25 18:29 UTC, biosimulations-daemon commented
:tada: This PR is included in version 9.62.0 :tada:

The release is available on [GitHub release](https://github.com/biosimulations/biosimulations/releases/tag/v9.62.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: